- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
- .github/workflows/release.yaml
Automatically creates a Github release when a (semantic) `v*` git `tag` is pushed to the repository. This is typically done like this:
```
git checkout main
git pull upstream/main
RELEASE=0.1.0
git tag -a $RELEASE -m "Release ${RELEASE}"
git push upstream --follow-tags
```
This will trigger the `release` action workflow and create a Github release with release notes.
Alternatively, e.g. to create a release for an existing tag if it does not exist yet, the workflow supports the "dispatch" trigger. Go to `Actions -> Release -> Run Workflow` and enter the tag for which to create a (non-existing) release.
Example output for a first `v0.1.0` release:
(Note that Github replaces the issue refs in () with the full issue name here in this comment. This is not the case in the release notes though, …
> Add release automation

- example_test.go
Add a `go test`-able example which also shows up in godoc and https://pkg.go.dev/ and also allows user to run ("interact") with the code.
Closes: #70
> Add godoc example

- core_matcher.go
- flatten_json_test.go
- match_set.go
- match_set_test.go
- addX: adding length check to avoid copying the map if nothing was changed.
- Introducing addXSingleThreaded which allows update-in-place in single-threaded usages.
```
name \ time/op                          benchs/1_baseline  benchs/2_len_check  benchs/3_thread_safe_add  benchs/4_thread_safe_len_check
_Quamina-10                                   48.0µs ± 0%         33.9µs ± 0%                6.6µs ± 0%                      6.8µs ± 0%
name \ alloc/op                         benchs/1_baseline  benchs/2_len_check  benchs/3_thread_safe_add  benchs/4_thread_safe_len_check
_Quamina-10                                   41.0kB ± 0%         30.4kB ± 0%                8.9kB ± 0%                      8.9kB ± 0%
name \ allocs/op                        benchs/1_baseline  benchs/2_len_check …
```
> matchSet.addX / matchSet.addXSingleThreaded performance improvements

- flatten_json.go
- flatten_json_test.go
This event:
```json
{ "message" : "docs: change \" -> \\" }
```
Would cause an error until now.
fixes: https://github.com/timbray/quamina/issues/150
> fix: double escaping in skipString

- .chglog/config.yml
This was supposed to have been part of the big v1.0-prepare PR but I fat-fingered it out of the commit when fighting git problems co-operatively with Micha.
> kaizen: Update config for kaizen

- PATTERNS.md
- README.md
- cl2_test.go
- core_matcher_test.go
- pattern.go
- pattern_test.go
- small_table.go
- value_matcher.go
- value_matcher_test.go
> pat: add prefix pattern

- flatten_json.go
- flatten_json_test.go
Hopefully this is a fairly straightforward bug fix.
There is a small bug in the flattener when skipping the remaining fields of an event after all nodes/fields in supplied patterns have been evaluated. In the case where one of the additional fields is an object (or an object inside an array), the flattener will exit early at the first `}` it encounters.
If there are additional fields to match, the flattener will attempt to continue processing the event. However, the event index will be incorrectly pointed at the end of the next object it encounters, rather than the end of the object currently being processed.
Take the following event and paths, for example:
```json
{ "nested": { "value": "something", "bad": {} } }
```
```json
[ "nested\nvalue", "anotherField" ]
```
When the flattener …
> fix: handle nested objects when skipping unused fields

- README.md
- anything_but.go
- cl2_test.go
- core_matcher.go
- field_matcher.go
- flatten_json.go
- nfa.go
- nfa_test.go
- prettyprinter.go
- prettyprinter_test.go
- shell_style.go
- shell_style_test.go
- small_table.go
- small_table_test.go
- stats.go
- value_matcher.go
- value_matcher_test.go
prevent state explosions with epsilon transitions
The introduction of proper NFA epsilon transitions - see https://swtch.com/~rsc/regexp/regexp1.html - totally fixed this problem. The most dramatic illustration is line 96 of shell_style_test.go. Previously, you could only use 20 or so shell_style patterns before an O(2**N) explosion leading to millions of states. Now you can add all 12K in the test file.  The `addPattern()` runs almost instantly, although matching slows down, a fair trade-off.
Once this is landed, we can start implementing all the cool stuff that was-ruler has without worry about exploding NFAs.
> addresses issue #188

- PATTERNS.md
- README.md
- cl2_test.go
- core_matcher.go
- go.mod
- pattern_test.go
- shell_style.go
- shell_style_test.go
Note that this is a semantic change so will lead to release 1.1.0.
> pat: remove limit of one * in shell style

- benchmarks_test.go
- cl2_test.go
- core_matcher.go
- field_matcher.go
- nfa.go
- prettyprinter.go
- shell_style_test.go
- small_table.go
- value_matcher.go
This adds the function `analyze()` to coreMatcher.  It visits all of the fieldMatcher and valueMatcher states and gathers statistics (at the moment, just the maximum nondeterministic concurrency).  For the moment, this is strictly an (extremely useful) tool for developers trying to optimize NFA construction/traversal.
Its output could be used in practice to increase the performance of the pathological case illustrated by `TestShellStyleBuildTime()`, which slows down to <10K/second when you add 13K wildcard patterns, but that
particular optimization requires much more thinking.
No public API yet, but this could evolve into something similar to Ruler's `MachineComplexityEvaluator` public API although I'm not happy with the metric that API generates.
Also in this commit: Miscellaneous code …
> kaizen: add analyzer, misc cleanup

- .github/workflows/benchmarks.yml
- match_set.go
- match_set_test.go
- nfa.go
- shell_style_test.go
- small_table.go
- value_matcher.go
We took a ~20% performance penalty with the introduction of NFAs (and thus full shellstyle support) and this is shown up particularly in numeric patterns. It turns out that while our data structure is designed to support NFAs, a lot of the FAs we generate are actually deterministic, i.e the combination of a state and a byte always causes a transfer to zero or one other state. Thus it is possible to traverse the FA without keeping track of multiple current/next states, vastly reducing the amount of memory management required.  This PR led to ~20% performance improvement on common cases, no change on shellstyle, probably >20% on numerically-heavy patterns. 20% is pretty good since half our CPU/elapsed time still goes into flattening the events.
> kaizen: Increase throughput with flexible FA traversal

- quamina.go
The information provided by flattenerSpecified is redundant and available by checking if flattener is nil.
> chore: drop Quamina.flattenerSpecified

- core_matcher.go
- field_matcher.go
- value_matcher.go
This improves the situation by closing down the api and enforcing the required type.
It also slightly reduces allocations and memory use and - at least on my system - improves benchmarking time for the whole system from 35.788s to 32.588s (but only one run each and 2 days apart...).
> chore: prefer atomic.Pointer to atomic.Value

- README.md
- numbits.go
Numeric comparisons now cover the entire range of float64 values.
> kaizen: Move to v1.4

- PATTERNS.md
- README.md
- pattern.go
- pattern_test.go
- prettyprinter.go
- value_matcher.go
- value_matcher_test.go
- wildcard.go
- wildcard_test.go
addresses: #322 - i.e. brings Ruler-compatible `wildcard` patterns to Quamina
> pat: add wildcard pattern

- numbits.go
... and drop a doc-reference to a function that was not ported from the original implementation.
The improvement will use sign extension for a right shift for int64. This will fill all bits with the sign bit. There's no need for another constant.
This was sensibly suggested by Raph Levien in a mastodon thread: https://mastodon.online/@raph/113071041069390831
> improvement: alternative numbits conversion

- .github/workflows/benchmarks.yml
- .github/workflows/dep-review.yaml
- .github/workflows/go-lint.yaml
- .github/workflows/go-unit-tests.yaml
- .github/workflows/release.yaml
- .golangci.yaml
- go.mod
- numbers_test.go
- numbits_test.go
This was necessitated by `go-unit-tests.yaml` containing
``
go install github.com/mfridman/tparse@latest
``
which uses the `toolchain` directive, not supported in go 1.19.  Note that AFAIK Quamina uses no post-1.19 features of Go.
> chore: bump go version to 1.22

- .github/workflows/go-unit-tests.yaml
- .gitignore
Manually upgrade to codecov v5 due to changes in their CLI which creates verification files causing our git dirty check to fail.
> Migrate to codecov v5

- go.mod
Comply with https://go.dev/doc/toolchain#version and address CodeQL warnings.
Closes: #396
> Add patch version to go.mod

- PATTERNS.md
- README.md
- REGEXP.MD
- cl2_test.go
- code_gen/qtest-main.not-go
- core_matcher_test.go
- pattern.go
- pattern_test.go
- prettyprinter.go
- prettyprinter_test.go
- regexp_nfa.go
- regexp_nfa_test.go
- regexp_parse.go
- regexp_parse_test.go
- regexp_reader.go
- regexp_reader_test.go
- regexp_samples_test.go
- regexp_validity_test.go
- small_table.go
- small_table_test.go
- stats.go
- value_matcher.go
partially addresses #66
A lot of code to parse regexps and build them into a tree from which an NFA can be generated.  It has a feature tracker and will reject quamina.AddPattern with a regexp that includes an unimplemented feature.  The only feature generated so far is ".". See REGEXP.md for details.
some of regexp_nfa.go is weakly tested since only "." is implemented so far and some code not related to that can't be reached in production.
valueMatcher.addTransition considerably re-organized for simplicity
> pat: regexp infra plus dot
