.github/dependabot.yml, .github/workflows/codeql-analysis.yaml, .github/workflows/dep-review.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unit-tests.yaml
Changes:
Notes:
- unit tests are failing (you're aware of this IMHO)
- golangci-lint tests are failing (see the errors in the code annotations)
- Dependency review needs to be enabled for the repo to work
- You might want to enable branch protection to require certain CI workflows to pass before allowing to merge a PR (see ["enable required status checks"](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule))
Closes: #6 
=> Add Github Actions and Dependabot automation

README.md
Preview:
Since we're not using code coverage yet, I have commented this badge out.
Closes: #8
=> Add repository badges

.github/workflows/go-unit-tests.yaml
=> Use LFS and cache in unit tests

.github/workflows/go-lint.yaml
=> Use go v1.18 in linter

README.md
=> Fix broken badges

.codecov.yaml, .github/workflows/go-unit-tests.yaml, README.md
=> Add codecov.io support

flatten_json.go, flatten_json_test.go, numbers_test.go
Closes: #33
Improved coverage in the two files that really lacked it: flattenJSON and numbers
=> chore: improve test coverage

.github/workflows/go-lint.yaml, .github/workflows/go-unit-tests.yaml, testdata/citylots.jlines
=> Remove LFS and large file

core_matcher.go, flattener.go, live_pattern_state.go, live_pattern_state_test.go, matcher.go, pruner.go, pruner_test.go, quamina.go
=> chore: improve godocs, unexpose memState

flattener.go, name_tracker.go, quamina.go
=> chore: improve docstrings

doc.go, flattener.go, matcher.go, quamina.go, stats.go
=> chore: finish up docstrings

PATTERNS.md, README.md
=> chore: specification for Patterns

README.md, list_maker.go, list_maker_test.go, shell_style_test.go, small_table.go, small_table_test.go, stats.go, value_matcher.go
Related to #65 - addresses but does not fully resolve
=> code: reduce all NFAs to DFAs

README.md, field_matcher.go, flatten_json.go, flattener.go, list_maker.go, match_set.go, quamina.go, shell_style_test.go, small_table.go, value_matcher.go
Closes: #67
Improves docs to highlight potential performance problems with large numbers of AddPattern() calls for shellstyle Patterns.
=> chore: cleanup after NFA-DFA refactor

flatten_json.go, flatten_json_test.go
=> allow empty arrays and objects in json flattener

.github/workflows/benchmarks.yml, .gitignore, benchmarks_test.go, citylots_bench_test.go
- Run benchmarks on CI using https://github.com/benchmark-action/github-action-benchmark
- Adding CityLots benchmark
=> Benchmarks

PATTERNS.md, README.md, core_matcher.go, core_matcher_test.go, field_matcher.go, value_matcher.go, value_matcher_test.go
closes: #115
Thanks once again to [kylemcc](https://github.com/kylemcc) for finding this bug and providing the first unit test.
The solution here is clumsy and slow-ish but I think correct.
@yosiat Do we have a conflict with your big PR? There are some changes to field_matcher.go. Just wondering about which order is smartest to merge them in, after reviewing of course.
=> bug: Make exists:false work

flatten_json.go
Signed-off-by: Yosi Attias <yosy101@gmail.com>
=> chore: flatten_json: fix formatting

cl2_test.go, generic_machine_test.go
fixes: #172
The object of the game is to workaround GitHub issues.
=> fix: exclude ruler-sourced tests from unit test build

cl2_test.go, generic_machine_test.go
=> fix: Identify Ruler tests

.github/workflows/benchmarks.yml, .github/workflows/dep-review.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unit-tests.yaml, .github/workflows/release.yaml, .gitignore, cl2_test.go, generic_machine_test.go
Signed-off-by: Michael Gasch <15986659+embano1@users.noreply.github.com>
=> Update CI Workflows

CONTRIBUTING.md, README.md
=> docs: v1.0 touch-up

.github/workflows/benchmarks.yml, example_test.go, external_test.go, go.mod
Worth mentioning that the path is: quamina.net/go/quamina
=> kaizen: vanity import path

.github/workflows/benchmarks.yml
Adds https://github.com/benchmark-action/github-action-benchmark#pr-summary
@timbray see https://github.com/timbray/quamina/actions/runs/4391164905#summary-11926822902
=> Print benchmark summaries

README.md
Need a minor semver bump because we enhanced the API, allowing multiple *'s in shellstyle.
=> kaizen: prepare for release 1.1.0

README.md, REGEXP.md, code_gen/qtest-main.not-go, core_matcher_test.go, regexp_end2end_test.go, regexp_nfa.go, regexp_nfa_test.go, regexp_parse.go, regexp_reader.go, regexp_reader_test.go, regexp_samples_test.go, regexp_validity_test.go, value_matcher.go
=> pat: Add char classes and alts to regexp

README.md, REGEXP.md, core_matcher_test.go, regexp_end2end_test.go, regexp_nfa.go, regexp_nfa_test.go, regexp_parse.go, regexp_reader.go, regexp_reader_test.go, value_matcher.go
=> pat: Add parenthesized sub-regexp

.github/dependabot.yml, .github/workflows/benchmarks.yml, .github/workflows/codeql-analysis.yaml, .github/workflows/dep-review.yaml, .github/workflows/go-lint.yaml, .github/workflows/go-unit-tests.yaml, .github/workflows/release.yaml
This PR includes two commits that improve our CI/CD configuration:
• Fixed indentation in .github/dependabot.yml for the GitHub Actions package ecosystem
• Added version comments to all GitHub Actions to improve traceability
• Updated GitHub Actions dependencies:
• Updated actions/setup-go from unversioned to v5.5.0
• Updated actions/dependency-review-action to v4.7.1
• Updated golangci/golangci-lint-action to v8.0.0 with explicit version v2.1.6
• Removed unnecessary caching configurations:
• Removed actions/cache from benchmarks workflow
• Removed Go cache restoration steps from lint and unit test workflows
• Streamlined workflow configurations for better maintainability
=> fix: golangci-lint and dependabot
